name: Build

on:
    workflow_call:
        inputs:
            retention-days:
                description: "Number of days to retain the produced Docker image"
                type: number
                default: 1
            version:
                description: "Version to use for the built Docker images"
                type: string
                required: false

jobs:
    # Add your apps or services here. Example:
    #
    # build-app:
    #   name: Build App
    #   if: inputs.build-app == true
    #   runs-on: ubuntu-latest
    #   steps:
    #     - name: Checkout the updated source code
    #       uses: actions/checkout@v4

    #     - name: Set up Docker Buildx
    #       uses: docker/setup-buildx-action@v3

    #     - name: Build App
    #       uses: ./.github/actions/build-docker-image
    #       with:
    #         target: app
    #         args: |
    #           VERSION=${{ inputs.version }}
