name: Release to DEV

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    name: Version
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.set_short_sha.outputs.short_sha }}
    steps:
      - name: Set short SHA
        id: set_short_sha
        run: echo "short_sha=${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

  test-unit:
    name: Unit Tests
    uses: ./.github/workflows/_test-unit.yaml

  build:
    name: Build
    needs:
      - version
    uses: ./.github/workflows/_build.yaml
    with:
      version: DEV-${{ needs.version.outputs.version }}

  test-e2e:
    name: E2E Tests
    needs:
      - build
    uses: ./.github/workflows/_test-e2e.yaml

  publish:
    name: Publish
    needs:
      - build
      - test-unit
      - test-e2e
    uses: ./.github/workflows/_publish.yaml
    with:
      tag: latest
    secrets: inherit

  deploy:
    name: Deploy
    needs:
      - publish
    uses: ./.github/workflows/_deploy.yml
    with:
      images: ${{ needs.publish.outputs.images }}
    secrets: inherit

  tag:
    name: Tag
    needs:
      - publish
    uses: ./.github/workflows/_tag.yaml
    with:
      tag: DEV

  cleanup:
    name: Cleanup artifacts
    if: always()
    needs:
      - publish
    uses: ./.github/workflows/_cleanup-artifacts.yaml
