name: Release to PRODUCTION

on:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  version:
    name: Resolve version
    uses: ./.github/workflows/version.yml
    with:
      semver: none
      prerelease: false

  test-unit:
    name: Unit Tests
    uses: ./.github/workflows/test-unit.yml

  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      version: ${{ needs.version.outputs.new_version }}

  test-e2e:
    name: E2E Tests
    needs: build
    uses: ./.github/workflows/test-e2e.yml

  publish:
    name: Publish
    needs:
      - build
      - test-unit
      - test-e2e
    uses: ./.github/workflows/publish.yml
    with:
      tag: latest
      version-tags: true
    secrets: inherit

  deploy:
    name: Deploy
    needs: publish
    uses: ./.github/workflows/_deploy.yml
    with:
      tag: latest

  tag:
    name: Tag
    needs: publish
    uses: ./.github/workflows/_tag.yml
    with:
      tag: PRODUCTION
      version: ${{ needs.version.outputs.new_tag }}

  cleanup:
    name: Cleanup artifacts
    needs: publish
    uses: ./.github/workflows/_cleanup-artifacts.yml
