name: Build Docker image

inputs:
    target:
        description: "Target build stage in the Dockerfile"
        type: string
        required: true
    args:
        description: "Build arguments for the Docker build"
        type: string
        required: false

runs:
    using: composite
    steps:
        - name: Build image
          uses: docker/build-push-action@v6
          with:
              target: ${{ inputs.target }}
              tags: ${{ inputs.target }}:${{ github.sha }}
              outputs: type=docker,dest=${{ runner.temp }}/${{ inputs.target }}-docker-image.tar
              cache-from: type=gha,scope=${{ inputs.target }}
              cache-to: type=gha,mode=max,scope=${{ inputs.target }}
              build-args: ${{ inputs.args }}

        - name: Upload Docker image tarball
          uses: actions/upload-artifact@v4
          with:
              name: ${{ inputs.target }}-docker-image
              path: ${{ runner.temp }}/${{ inputs.target }}-docker-image.tar
              retention-days: 1
