name: Test

on:
  branch:
    master
  paths:
    - "sdk/**"

jobs:
  test:
    name: Test SDK package
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
          cache: "npm"
          cache-dependency-path: package-lock.json
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_PUBLISH_TOKEN}}

      - name: Install dependencies
        run: cd sdk && npm ci

      - name: Test SDK
        run: cd sdk && npm test