import { INestApplication } from "@nestjs/common";
import { OpenAPIObject, SwaggerCustomOptions, SwaggerModule } from "@nestjs/swagger";

export function generateOpenAPI(app: INestApplication, openapiBase: Omit<OpenAPIObject, "paths" | "openapi">) {
	return SwaggerModule.createDocument(
		app,
		{ ...openapiBase, openapi: "3.0.0" },
		{
			autoTagControllers: false,
			operationIdFactory: (controllerKey: string, methodKey: string) => `${controllerKey}.${methodKey}`,
		},
	);
}

/**
 * App agnostic function to add Swagger UI to a NestJS application. Adds niceties to standard SwaggerModule.setup().
 */
export function setupSwagger(
	path: string,
	app: INestApplication,
	openapiDocument: OpenAPIObject,
	swaggerUiOptions: SwaggerCustomOptions["swaggerOptions"] = {},
) {
	path = normalizePathPrefix(path);

	// SwaggerModule does not add the OpenAPI paths for the paths generated by itself, so we need to add them manually
	const openapiPaths = generateOpenapiPaths(path, openapiDocument);
	Object.assign(openapiDocument.paths, openapiPaths);

	function openapiTagSorter(a: string, b: string) {
		if (a === "Root") return -1;
		if (b === "Root") return 1;
		return a.localeCompare(b);
	}

	// because standard operation sorts dashes before slashes
	// ie /user-profile comes between /user and /user/{id}
	// this function sorts by path parts
	// ie /user-profile comes after /user and /user/{id}
	function operationsSorter(a: Map<"path" | "method", string>, b: Map<"path" | "method", string>) {
		const aParts = a.get("path")?.split("/");
		const bParts = b.get("path")?.split("/");

		const methodsOrder = ["options", "get", "query", "post", "put", "patch", "delete"];

		if (!aParts || !bParts) return 0;

		while (true) {
			if (!aParts.length && !bParts.length) {
				return methodsOrder.indexOf(a.get("method")!) - methodsOrder.indexOf(b.get("method")!);
			}

			if (!aParts.length) return -1;
			if (!bParts.length) return 1;

			if (aParts[0].startsWith("{") && !bParts[0].startsWith("{")) return 1;
			if (!aParts[0].startsWith("{") && bParts[0].startsWith("{")) return -1;

			const result = aParts.shift()!.localeCompare(bParts.shift()!);
			if (result !== 0) return result;
		}
	}

	SwaggerModule.setup(path, app, openapiDocument, {
		swaggerOptions: {
			tagsSorter: openapiTagSorter,
			operationsSorter: operationsSorter,
			persistAuthorization: true,
			showCommonExtensions: true,
			displayOperationId: true,
			...swaggerUiOptions,
		},
	});
}

function generateOpenapiPaths(path: string, document: OpenAPIObject): OpenAPIObject["paths"] {
	return {
		[path]: {
			get: {
				tags: ["Root"],
				summary: "This SwaggerUI page",
				operationId: "viewSwaggerUI",
				parameters: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: { "application/html": { schema: { type: "string" } } },
					},
				},
			},
		},
		[`${path}-json`]: {
			get: {
				tags: ["Root"],
				summary: "The OpenAPI document in JSON",
				operationId: "getOpenAPIJSON",
				parameters: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: { "application/json": { schema: { type: "string" } } },
					},
				},
			},
		},
		[`${path}-yaml`]: {
			get: {
				tags: ["Root"],
				summary: "The OpenAPI document in YAML",
				operationId: "getOpenAPIYAML",
				parameters: [],
				responses: {
					"200": {
						description: "OpenAPI document",
						content: { "application/yaml": { schema: { type: "string" } } },
					},
				},
			},
		},
	};
}

function normalizePathPrefix(path?: string) {
	if (!path) return "";

	return path
		?.replace(/\/$/, "") // remove trailing slash
		?.replace(/^([^/])/, "/$1"); // ensure leading slash
}
